name: azure_app_config
version: 0.15.2
description: A Dart package to communicate with Microsoft Azure App Configuration.
repository: https://github.com/iamwalter/azure_app_config

environment:
  sdk: '>=2.18.1 <4.0.0'
dependencies:
  crypto: ^3.0.2
  dio: ^5.1.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  meta: ^1.8.0
  
dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.2.0
  http_mock_adapter: ^0.4.4
  json_serializable: ^6.5.3
  mockito: ^5.3.2
  test: ^1.21.6
  very_good_analysis: ^4.0.0+1 
  
  